### ISSUE TITLE
Process Substitution Fails

### ISSUE THREAD

**Issue by adam-grant-hendry** [cresh-io/action-gpg#4]
The process substitution

```bash
--passphrase-file <(echo ***)
```

in `action.yml`

https://github.com/cresh-io/action-gpg/blob/69c283c829f9f89f282f110f705db67a2b263777/action.yml#L53-L55

fails in instances where GitHub Actions falls back to using `sh` (`sh` does not support process substitutions unless POSIX mode is turned off with `set +o posix`).

Per the GitHub Docs for [`jobs.<job_id>.steps[*].shell`](https://github.com/cresh-io/action-gpg/blob/69c283c829f9f89f282f110f705db67a2b263777/action.yml#L53-L55), `shell: bash` behaves as follows:

> The default shell on non-Windows platforms with a fallback to `sh`. When specifying a bash shell on Windows, the bash shell included with Git for Windows is used.

Please add `set +o posix` to step `Import GPG Key`.

**Comment by sylver** [comment]
Hi @adam-grant-hendry 

Sorry for the delay, but we took your issue into account and pushed a few improvements in a new `v2` tag.
